### ISSUE TITLE
Erreur lors de la commande

### ISSUE THREAD

**Issue by Wyman42** [Aymkdn/assistant-freebox#1]
Hello, 
Tout fonctionnait bien jusqu'à que je remplace le Freebox Serveur. Depuis j'ai cette erreur.
![assistant01](https://user-images.githubusercontent.com/33159735/33807850-40b2a586-dddd-11e7-8f80-b9f118ce2bf9.PNG)
Pourtant, j'ai tout vérifier : code télécommande, adresse IP, AirMedia activé....
(assistant tourne sur un Raspi 2)

**Comment by Aymkdn** [comment]
Supprime le app_token de ton fichier de configuration. Quand tu relanceras le programme il faudra réauthoriser le programme sur la nouvelle freebox.

**Comment by Wyman42** [comment]
Exact.... merci !
