### ISSUE TITLE
répétitions des commandes

### ISSUE THREAD

**Issue by adrienvia** [Aymkdn/assistant-freebox#10]
bonjour, jusqu'à maintenant ça marchait super bien, mais là, je sais pas pourquoi, mais j'ai l'impression qu'il double toutes les commandes, si je demande de zapper sur tf1, il va appuyer sur 1 et 1, donc 11... et pour tout le reste aussi, j'ai l'impression que c'est pareil pour toutes les commandes, fléches, red, ok... tout ça. je sais pas trop ou regarder dans les paramètres...

**Comment by Aymkdn** [comment]
Tu as dû lancer le programme 2 fois sur ton ordi.

**Comment by adrienvia** [comment]
effectivement, au temps pour moi, j'avais utilisé récemment la méthode pm2, car j'en avais une autre jusqu'à maintenant, pour le démarrage automatique sur raspberry, mais il ne se lançait pas à tous les coups, j'ai fais seulement avec pm2, et c'est niquel =) merci
