### ISSUE TITLE
Option Multi TV

### ISSUE THREAD

**Issue by GabTen** [Aymkdn/assistant-freebox#11]
Bonjour,

Je dispose de deux freebox player. Y'a t-il un moyen de contrôler les deux?
Par exmple en ajoutant un player dans le fichier configuration.json?

Merci

**Comment by Aymkdn** [comment]
Non, ce n'est pas prévu. Tout simplement parce qu'il faudrait des commandes spécifiques depuis le Google Home pour chaque box, par exemple "OK Google sur la Freebox du salon zappe sur TF1". Pas très pratique.... Aussi niveau de la création des applets ça serait assez chiant aussi.

**Comment by GabTen** [comment]
Merci pour votre réponse rapide (et aussi merci pour votre travail)
En fait j'avais pensé au fonctionnement suivant:

Disons par exemple que j'ai un freebox player dans le salon et l'autre dans une chambre.
Sur iftt je créé un applet pour l'allumage des freebox et un pour l'extinction en utilisant "create an applet with a text ingredient".

Par exemple "Allume la télévison #" . # correspondand à "salon" ou "chambre"
Cela allumerais alors la freebox de mon choix en sélectionnant dans configuration.json les informations de la box correspondant au mot "salon" ou au mot "chambre".

Pour le reste des applets si je veux par exemple monter le son: je dis "Augmente le son" comme cela est fait actuellement.
La commande est alors envoyé et le pluggin fait alors les vérifications suivantes:

--> Si la freebox salon est allumée 
    --> exécute la commande sur la freebox du salon
--> Si la freebox salon est éteinte
    --> vérifie si la freebox chambre est allumée
        --> si oui: alors exécute la commande sur la freebox de la chambre  
        --> si non: ne fait rien

Par contre fonctionnement comme celui là impliquerait que la freebox du salon est prioritaire sur les commandes et qu'on ne peut utiliser qu'une seule freebox à la fois.

Qu'en pensez vous?

**Comment by Aymkdn** [comment]
Sur le papier ça pourrait se faire, mais ça m'oblige à tout recoder pour inclure ce type de paramètre... Et la vérification de la Freebox allumée ne fonctionne pas toujours sur toutes les Freebox !

Donc si c'est vraiment un besoin, je peux le noter comme amélioration possible, mais je ne pourrai pas le coder dans un futur très proche :-/

**Comment by GabTen** [comment]
Je comprends. N'ayant pas encore codé en js jusqu'à présent, j'hésitais à me lancer sur la modification de votre code moi-même.
Si j'ai le temps de m'y mettre je vous ferais part de mes avancements.

**Comment by navjul** [comment]
Bonjour,

J'y vais également de mon commentaire pour dire merci pour ce programme bien sympa ! la doc est bien faite, j'ai pu m'en sortir simplement et rapidement ! J'ai même pu rajouter des applets pour effectuer des actions personnalisées, c'est top ! 

Si je rebondis ici, c'est pour indiquer que, je serai également grandement preneur d'une solution pour pouvoir piloter deux freebox player !

Enfin, si quelqu'un peut m'indiquer comment faire pour faire tourner la commande node index.js en tâche de fond, je suis preneur de la méthode sous Linux.

Merci d'avance si cela peut être réalisé à l'avenir !

**Comment by Aymkdn** [comment]
Tâche transférée vers https://github.com/Aymkdn/assistant-plugins/issues/163 afin de centraliser
