### ISSUE TITLE
applet ifttt

### ISSUE THREAD

**Issue by superiuspi** [Aymkdn/assistant-freebox#13]
Bonjour,
question bête pourquoi ne vois -t-on pas le code des commandes envoyées à pushbullet quand on active tes applets sur IFTTT ?
Peux-tu nous les donner ?
Sinon super boulot !!
![ifttt](https://user-images.githubusercontent.com/40075644/44772068-2e37e480-ab6d-11e8-8e02-271abef8df9a.jpg)

Merci

**Comment by Aymkdn** [comment]
C'est IFTTT qui fonctionne comme ça lorsqu'on crée des templates... et je ne peux pas l'afficher pour ceux qui l'utilisent.

Mais tout est assez bien expliqué dans la documentation : https://aymkdn.github.io/assistant-plugins/?plugin=freebox#personnalisation

Si t'as besoin du code précis d'une applet précise, je peux te le fournir.

**Comment by superiuspi** [comment]
Ok merci,
je veux juste accéder à mon NAS au lieu du hdd de la freebox .
Et faire des recherche dedans ou lancer un fichier directement.
Merci pour ta réponse.

**Comment by superiuspi** [comment]
pourtant la suivante "Allume la télé via la Freebox avec Google Home" est editable jusqu'a pushbullet ...

**Comment by Aymkdn** [comment]
Regarde ici https://github.com/Aymkdn/assistant-plugins/issues/66

**Comment by Aymkdn** [comment]
> pourtant la suivante "Allume la télé via la Freebox avec Google Home" est editable jusqu'a pushbullet ...

Ah oui.... Je vois qu'ils ont ajouté une option pour afficher/cacher chaque partie. Je ne comprends pas pourquoi celui-ci a pris l'option "afficher" alors que j'ai copié/collé toutes les templates ^^

Bon, en soit, c'est pas plus mal que le "code" soit caché je pense.... En plus j'ai créé 110 templates, donc je ne vais pas m'amuser à toutes les ré-éditer pour afficher cette partie là maintenant que l'option est dispo ;-)

J'ai essayé de bien expliquer dans la doc pour les aventuriers qui voudraient créer leurs propres applets.

**Comment by superiuspi** [comment]
Merci pour le lien mais le problème c'est que en fonction de ce qui est allumé chez moi mon nas n'est plus dans la même position dans la liste !
Bon après ma femme me diras : tu prends la télécommande et tu cliques !!!
Mouaiii sauf que je fais de la domotique madame ! ( ou presque...)
Le truc chiant c'est aussi que j'utilise google home et je dois refaire mes plugin dans les comptes de toute la famille ....  j'ai pas encore trouvé les templates .

**Comment by Aymkdn** [comment]
> Merci pour le lien mais le problème c'est que en fonction de ce qui est allumé chez moi mon nas n'est plus dans la même position dans la liste !

Ah... Dans ce cas, je n'ai pas de solution...

> Le truc chiant c'est aussi que j'utilise google home et je dois refaire mes plugin dans les comptes de toute la famille ....

Comment ça ? Nous on est deux à la maison (avec 2 comptes configurés sur un seul Google Home), et ça fonctionne pour nous deux les commandes.... même si IFTTT n'est connecté qu'à mon compte Google à moi...

> j'ai pas encore trouvé les templates

Les templates se créent via https://platform.ifttt.com/dashboard
