### ISSUE TITLE
search path + autre commande

### ISSUE THREAD

**Issue by adrienvia** [Aymkdn/assistant-freebox#15]
Bonjour, j'ai un petit soucis, je souhaite utiliser la commande folder, pour trouver le dossier demandé, et après faire d'autres actions, sauf que je ne sais pas quoi mettre exactement dans la commande pour pushbullet, (IFTTT) le titre"Assistant" bien sur, et le message: "freebox_..." mais après je sais pas, si je mets freebox_folder $ ça ne marche pas, et du coup y'a un détails que je n'ai pas bien compris pour qu'il recherche bien le texte que j'ai dit ($) en tant qu'ingredient.

merci à vous.

**Comment by Aymkdn** [comment]
Donc la commande `folder` fonctionne en lien avec [`search_path`](https://aymkdn.github.io/assistant-plugins/?plugin=freebox#param-tre-search_path)

**Qu'as-tu mis dans `search_path` ?**

Ensuite, la création de l'applet IFTTT va donner quelque chose comme ça :
1. Créer une nouvelle applet dans IFTTT : [https://ifttt.com/create](https://ifttt.com/create)
2. Cliquer sur `this` puis choisir Google Assistant
3. Choisir la carte **« Say a phrase with a text ingredient »**
4. Dans « What do you want to say? » mettre une phrase, par exemple : `Va dans le dossier $`
    Le symbôle `$` sera remplacé par Google par ce qui sera prononcé
5. Remplir les autres champs de la carte
6. Cliquer sur `that` puis choisir Pushbullet
7. Choisir la carte **« Push a Note »**
8. Dans le champs « Title », mettre **Assistant**
9. Dans le champs « Message », mettre `freebox_folder $`

Ensuite si le dossier s'appelle "Mes Séries", tu peux prononcer : `OK Google, va dans le dossier Mes Séries`

Et, si comme moi, tu as un dossier qui porte le nom d'une série, tu peux dire : `OK Google, va dans le dossier Star Trek` par exemple.

Teste avec ton assistant sur ton téléphone, afin de voir comment Google reconnait ce que tu lui dis.

**Comment by adrienvia** [comment]
justement c'est bien ça que j''arrive pas à comprendre, en effet quand j'utilise la commande va dans le dossier Star Trek par exemple, (avec votre applet IFTTT à vous du coup) ça fonctionne, google assistant me met bien qu'il recherche le dossier Star Trek, et après tout se passe bien et il va dans le dossier Star Trek et en checkant avec mp2 monit, je vois bien que tout fonctionne, commande reçu: freebox_folder Star Trek ...

mais quand je créé moi même l'applet, avec tout ça, quand je lance le ok google, va dans le dossier Star trek, je vois bien qu'il me répond qu'il va dans le dossier Star trek, mais sur pm2 monit, je vois commande reçu: freebox_folder $ ... et pas Star trek... et du coup ça ne marche pas...

et d'après votre réponse c'est bizarre, parce que c'est bien ce que j'ai mi qu'il faut mettre...

**Comment by Aymkdn** [comment]
En fait, étape 9 je me suis trompé. Tu devrais avoir : `freebox_folder {{TextField}}` que tu obtiens grâce au bouton "Add Ingredient" (en supposant que tu as bien sélectionné "Say a phrase with a text ingredient" quand tu as créé l'applet) :
![capture](https://user-images.githubusercontent.com/946315/46261659-169aa580-c4f7-11e8-8ae8-96364b37c0d7.PNG)

**Comment by adrienvia** [comment]
ah oui, je me disais bien que ça servait à quelque chose cet "add ingredient"... j'aurai du tester un peu tout ça avant... du coup ça fonctionne bien, mais j'ai un autre problème... XD j'ai bien le $ (XYZ) pris en compte dans la commande reçu freebox_folder XYZ, mais après un petit durée de la vérification de la freebox allumée : ...ms, j'ai direct commande ... excecuté, et pas les commandes pour aller dans le dossier comme avec un va dans dossier $

**Comment by Aymkdn** [comment]
Peux-tu me faire une capture d'écran car j'ai du mal à comprendre...

**Comment by adrienvia** [comment]
![sans titre 1](https://user-images.githubusercontent.com/33934617/46261813-231ffd80-c4f9-11e8-94b7-c1833eaffe23.jpg)

**Comment by adrienvia** [comment]
dans cet exemple, j'ai juste rajouté un okay, pour lire le 1er fichier dans le dossier... ce que je crois

**Comment by Aymkdn** [comment]
Pour info, tu sais que tu peux installer [assistant-notifier](https://aymkdn.github.io/assistant-plugins/?plugin=notifier) pour avoir un retour vocal sur la commande ? Ça te dira si le dossier a été trouvé ou pas.

Ensuite j'ai encore un peu du mal à comprendre. Tu veux dire que quand tu lui dis "Va dans le dossier Maniac", il y va et ça fonctionne, mais si tu lui redis "Va dans le dossier Maniac" ça ne fonctionne plus ?

**Comment by adrienvia** [comment]
non non, quand ça fonctionne c'est avec votre applet à vous, du va dans le dossier, que j'ai directement emprunté via IFTTT, quand ça marche pas, c'est un autre applet que j'ai créé, ou je dis de chercher le dossier et de mettre okay sur le 1er fichier, mais même quand je simplifie à freebox_folder textfield seulement ça ne fonctionne pas non plus. alors qu'il n'y a pas de différence avec votre applet, par rapport à ce que vous avez mi au début (mais si ça va pas plus loin, il doit pas trouver le dossier alors... il faudrait que j'essaye avec assistant-notifier, mais je suis seulement sur google assistant sur mobile

**Comment by Aymkdn** [comment]
Aaaaa OK ! En fait tu dois avoir ça dans ton applet : 
`freebox_folder {{TextField}}|freebox_OK`

**Comment by Aymkdn** [comment]
![capture](https://user-images.githubusercontent.com/946315/46262025-da1d7880-c4fb-11e8-9fdf-01dcab18c412.PNG)

**Comment by adrienvia** [comment]
aaah, oki, c'est pour ça que je vous demandais en fait, parce qu'en empruntant votre applet, je ne peux pas voir la deuxième partie de l'applet, et j'avais pas les détails pour pushbullet ;) j'aurai du commencer à expliquer mieux :P
