### ISSUE TITLE
freebox_folder besoin d'explications

### ISSUE THREAD

**Issue by FredSan83** [Aymkdn/assistant-freebox#18]
Salut Aymeric,
Il y a quelque chose que je n'ai pas pigé dans cette commande.
Je cherche à atteindre des dossiers qui jusqu'à maintenant sont soit dans "Mes Vidéos", soit dans "Mes photos".
Pour que la recherche puisse s'appliquer au travers du disque de la FB, même si c'est un peu plus long, j'ai mis "search_path": "/Disque dur/",
Tant que le dossier est dans "Mes Vidéos" cela marche très bien, même à un niveau profond, mais impossible de trouver un dossier dans "Mes photos" même de tout premier niveau.
Je remarque dans la console que les ordres passés commencent toujours par "home/home/right/ok" alors que je m'attendais à voir du "home/home/left/ok" pour le dossier "Photos".

Cette commande est-elle exclusive au dossier "Vidéos" ?

PS: j'ai bien eu ton message à propos du cloud.

Cdlt

**Comment by Aymkdn** [comment]
> Cette commande est-elle exclusive au dossier "Vidéos" ?

Oui, cette commande est faite pour le dossier Vidéos.

**Comment by FredSan83** [comment]
Ah merde !
Va falloir que je fasse mes diaporamas dans les vidéos ! :)

**Comment by FredSan83** [comment]
Salut Aymeric,
Je me suis donc amusé à créer deux types de dossiers dans "Mes vidéos"
Un pour les photos nommé "Diaporama" avec un dossier de photos à jouer en diaporama
Un dossier "Musique" où j'ai mis deux albums

Sur IFTTT, j'ai créé deux applets à peu près identiques mais aux comportements légèrement différents en fonction du contenu des dossiers lorsqu"on veut lire tout le contenu à la suite
Pour les diaporamas l'ordre sera : Ok google, diaporama $
Ingrédient PB : freebox_folder {{TextField}}|freebox_ok,wait50,play
Pour les vidéos et musiques : Ok Google, Album (ou série) $
Ingrédient PB : freebox_folder {{TextField}}|freebox_green,down*5,ok (on passe ici par le menu "jouer tous")
On peut par la suite jouer avec les fonctions pause, lecture, précédent, suivant etc...

Désolé de redire ici des choses que tu connais forcément mais j'ai pensé aux autres lecteurs et c'est aussi pour en arriver aux deux points suivants:
1) Supposons que tu regardes la télé et décides d'écouter un album. Si tu te goures dans le titre, la commande folder ne va pas avoir d'impact mais les commandes après le pipe seront exécutées. N'y a-t-il pas un moyen pour l'éviter ? (faire une espèce de "break"). Je pense notamment, comme j'ai pu le lire dans une autre issue, aux personnes âgées qui, dans cet exemple, vont se retrouver en "pause", déclencher le time shifting et ne plus savoir s'en sortir (c'est le cas de ma mère ! ;)).
2) Il est dommage de désorganiser la freebox pour arriver à cette fin. Est-il vraiment impossible de repérer  dans quel dossier "de base" (Vidéos, photos ou musique) se trouve le dossier recherché ou ne pourrait-on pas passer le dossier en argument à PB ? (je ne suis pas assez calé pour y répondre)

En attendant, si tu trouves ces deux applets intéressantes, tu peux les reprendre à ton compte, voire les améliorer, et les publier avec un statut public (ça non plus je ne sais pas faire dans IFTTT).

@+

**Comment by Aymkdn** [comment]
> N'y a-t-il pas un moyen pour l'éviter ?

Non...

> Est-il vraiment impossible de repérer dans quel dossier "de base" (Vidéos, photos ou musique) se trouve le dossier recherché ou ne pourrait-on pas passer le dossier en argument à PB

Oui c'est possible. Mais t'as un cas vraiment très particulier et rare.

**Comment by FredSan83** [comment]
Salut Aymeric,

Je reviens un peu tard, puisque tu as eu le temps de fermer cette issue.
Dans ton dernier post, dernière ligne, je suppose que tu as voulu dire "tu ES un cas rare".

Loin d'être vexé, le "cas rare" il s'est pris en main et, peut-être, voulant se sentir moins rare, a entrepris d'apporter sa pierre à un édifice déjà bien bâti  ! ;-)

Plus sérieusement, sur la base de ta fonction freebox_folder, j'ai ajouté les fonctions :
freebox_album : permet de trouver un dossier dans "/Disque dur/Musiques"
freebox_diaporama : permet de trouver un dossier dans "Disque dur/Photos"
Comme dit plus haut, on complètera dans PB les commandes supplémentaires pour sélectionner le contenu des dossiers et "jouer" tous les fichiers à la façon d'un CD ou d'un diaporama.

Les différentes "fonctions" n'ont pas été beaucoup changées, seule goTofolder à maintenant 2 paramètres au lieu d'un.
Je ne suis pas un spécialiste du codage mais pense avoir "commenté" les lignes. Je n'ai pas indenté volontairement les commentaires pour qu'ils soient plus repérables.

Si cela te dit de  jeter un oeil, comment fait-on pour te passer le freebox.js ?
Je te laisserai seul juge pour l'intégrer ou non en tant qu'amélioration.

Cdlt

**Comment by Aymkdn** [comment]
Tu peux poster ton code là : https://gist.github.com

**Comment by FredSan83** [comment]
Pas habitué de github, j'espère que tu pourras le récupérer. J'ai fait attention à ce que le gits soit public.
C'est là : https://gist.github.com/FredSan83/7c2198020d418f61a55f7687d6ada4d4

**Comment by Aymkdn** [comment]
Je viens de mettre à jour en version 2.0.12

J'ai décidé de procéder différemment de toi. Voilà les modifications : 

- ajout d'une commande `photos` pour aller dans "Mes Photos" et `musiques` pour aller dans "Mes Musiques"
- concernant l'utilisation de `folder`, par défaut ça continue à regarder dans `Mes Vidéos`, mais il est possible de modifier ce comportement en fournissant un "paramètre" à `folder`. Par exemple tu veux aller dans le répertoire "CLASSIQUE" et tu veux réduire le scope à `/Disque dur/musiques/GENRE` (donc le répertoire "GENRE" de "Mes Musiques"), alors dans ce cas tu mettras la commande : `folder{/Disque dur/musiques/GENRE/} CLASSIQUE` et il va donc chercher là où tu lui dis, puis se diriger dans "Mes Musiques" puis le bon répertoire

**Comment by FredSan83** [comment]
Bsr,
Je rentre un peu tard pour tester immédiatement. J'essaie de mettre à jour ce soir et te faire le retour qui va bien.
Tu as eu parfaitement raison de reprendre le truc à ta sauce, c'est encore plus ingénieux, autant compréhensible par M. ToutLeMonde :)
@+

**Comment by FredSan83** [comment]
Bon, désolé pas de test ce soir car il doit y avoir un souci avec npm comme nous l'avions évoqué dans l'issue [#215](https://github.com/Aymkdn/assistant-plugins/issues/215).
J'ai fait l'update comme d'hab, la console m'indique bien que je suis en 2.0.13 au niveau assistant plugin, en v2.0.12 au niveau assistant-freebox mais le freebox.js du package est toujours le mien avec mes commandes album et diaporama.
J'ai retenté un update il y a moins d'une heure et ça ne charge plus. J'ai le prompt du dossier dans le cmd.exe
On verra demain.

**Comment by Aymkdn** [comment]
Dans ce cas tu peux tenter : 
```
npm uninstall assistant-freebox
npm install assistant-freebox
```

Pour le réinstaller

**Comment by FredSan83** [comment]
J'ai dû en passer par là !

J'ai modifié mes commandes PB mais la box n'est pas dispo. Je testerai tout à l'heure quand la maisonnée pioncera !!! (j'vais faire gueuler GH et mes albums de musique ça leur apprendra à m'emmerder avec leurs feuilletons à la con) ;-)=)

**Comment by FredSan83** [comment]
Un seul mot : GENIAL, ça marche nickel !

Pour ceux qui auraient suivi ce thread et qui seraient intéresser par les applets Diaporama et Album, j'édite ci-dessous ce que j'avais taper plus haut,  avec ta nouvelle fonction :

Sur IFTTT, j'ai créé deux applets à peu près identiques mais aux comportements légèrement différents en fonction du contenu des dossiers lorsqu"on veut lire tout le contenu à la suite
Pour les diaporamas l'ordre sera : Ok google, diaporama $
Ingrédient PB : freebox_folder{/Disque dur/Photos/} {{TextField}}|freebox_ok,wait50,play
Pour les albums : Ok Google, Album $
Ingrédient PB : freebox_folder{/Disque dur/Musiques/} {{TextField}}|freebox_green,down*5,ok (on passe ici par le menu "jouer tous")

Bon, je pense qu'on a fait le tour de cette issue et que tu vas pouvoir la fermer.  On se retrouve sur le sujet "Cloud" !

@+
