### ISSUE TITLE
Monter/Baisser le son marche mal

### ISSUE THREAD

**Issue by lmaiaux** [Aymkdn/assistant-freebox#19]
Bonjour,

Merci pour la super appli !

J'ai le meme problème que le ticket #7 (fermé)
J'ai aussi joué avec le réglage freebox du délai avant répétition de la télécommande (en le passant du défaut=400ms au minimum=200ms) et en augmentant delay_volume (à une valeur supérieure au réglage freebox).
Ca marche mieux mais ce n'est pas l'idéal : le son monte de 5 barres environ en 5 à 10s.

Une autre possibilité est de poster une seule url avec le paramètre long, soit http://hd1.freebox/fr/...key=vol_inc&long=true

Pour moi, ca marche bien mieux : ca bouge de 10/12 barres et c'est immédiat.

Serait-il possible de modifier assistant-freebox pour utiliser cette façon de monter/baisser le son, au moins comme méthode alternative choisie avec un nouveau paramètre de configuration ?

Merci beaucoup et a+

**Comment by Aymkdn** [comment]
Je peux rajouter une commande spéciale, oui. Je ne suis pas chez moi ce week-end, mais je regarderai ça en début de semaine !

**Comment by lmaiaux** [comment]
Super !
Merci et bon we

**Comment by lmaiaux** [comment]
J'ai pas pu attendre :-)
Pour info, ci-dessous le patch que j'ai appliqué à freebox.js et qui fonctionne chez moi : 

[patch_long_change_vol.txt](https://github.com/Aymkdn/assistant-freebox/files/2922244/patch_long_change_vol.txt)

**Comment by Aymkdn** [comment]
Du coup, le `long=true` est suffisant pour que cela fonctionne, ou tu es également obligé de modifier le délai entre les commandes de volume ?

**Comment by lmaiaux** [comment]
(desole, pas d'accents car clavier qwerty)

Avec long=true, je n'utilise pas le delay_volume car je poste une seule commande vol_inc ou vol_dec (j'ai cree des commandes IFTTT associees avec un seul freebox_soundUp2 ou freebox_soundDown2).

Question subsidiaire : je lance node sur macos mais pushbullet se deconnecte assez rapidement. Ca peut aussi etre du a Avast ou a l'economiseur d'ecran ? Si ca vient d'Avast, connais-tu un autre antivirus gratuit et correct sur macos ?

Merci

**Comment by Aymkdn** [comment]
Je viens de publier la version 2.0.12 qui inclue désormais les commandes `soundLongDown` et `soundLongUp`. Je t'invite à mettre à jour et à les utiliser

> Question subsidiaire : je lance node sur macos mais pushbullet se deconnecte assez rapidement. Ca peut aussi etre du a Avast ou a l'economiseur d'ecran ?

Cela peut en effet être dû à Avast. L'économiseur d'écran, à priori non, sauf s'il met ton disque dur en veille par exemple.

> Si ca vient d'Avast, connais-tu un autre antivirus gratuit et correct sur macos ?

Les anti-virus sur MacOS ne sont pas forcément utiles, surtout si tu gardes ton OS à jour et que tu n'installes que les logiciels approuvés par Apple. Si tu souhaites vraiment en installer un, tu peux toujours chercher sur le Net ce qu'ils proposent comme solution.
