### ISSUE TITLE
problème d'arret et démarrage

### ISSUE THREAD

**Issue by superiuspi** [Aymkdn/assistant-freebox#20]
Bonjour,
depuis quelque temps l'orque j'utilise la commande vocale google via ifttt d’arrêt de la freebox , je vois le clignotement ,l’écran semble s'éteindre de 2 secondes puis reviens la ou il était .
Donc pas d'arret.
J'utilise les commandes pres construite du site .

Pour le démarrage on dirait qu'il clignote 2 fois pour démarrer .
Une idée ?

**Comment by Aymkdn** [comment]
J'ai du mal à comprendre. Tu veux dire que quand tu lui dis d'arrêter la Freebox il l'arrêté puis la rallume ? D'autres commandes s'exécutent en double, par exemple le changement de chaîne ?

**Comment by superiuspi** [comment]
Oui en effet je viens de me rendre compte que le changement de chaine s'exécute aussi en double ...

**Comment by Aymkdn** [comment]
C'est donc que tu as deux fois `assistant-plugins` de lancé sur ta machine. Je ne connais pas ta configuration, mais sûrement que tu as `pm2` qui le lance au démarrage, + toi qui l'as lancé manuellement. Il faudrait donc que tu arrêtes une de ces deux sessions.

Tu peux aussi te tourner vers la version dans le cloud du plugin Freebox : https://assistant.kodono.info/freebox/

**Comment by superiuspi** [comment]
Bien vu en fait j'ai 2pi et assistant plugin sur les deux ... Merci.
