### ISSUE TITLE
Documentation manquante pour app_token

### ISSUE THREAD

**Issue by fjouault** [Aymkdn/assistant-freebox#21]
Bonjour,

Merci pour cette application bien pratique.
Puis-je suggérer l'ajout d'une section sur le paramètre app_token dans la doc (voir ci-dessous pour un exemple d'à quoi ça pourrait ressembler) ?

Cordialement,

Frédéric

---------------------------

### Paramètre `app_token`

La valeur de ce paramètre est un jeton d'authentification avec l'API Freebox.
Bien que ce paramètre soit généralement géré automatiquement, il peut parfois s'avérer nécessaire de le supprimer pour forcer sa recréation lors du prochain démarrage. C'est notamment le cas si l'on révoque l'accès de l'application assistant-freebox depuis Freebox OS ou encore si l'on change de Freebox.

**Comment by Aymkdn** [comment]
Ok, merci pour la suggestion ! Je regarde ça demain quand je serai avec mon ordi 😉

**Comment by Aymkdn** [comment]
C'est fait !

**Comment by fjouault** [comment]
Merci !
