### ISSUE TITLE
Absence des chaînes optionelles

### ISSUE THREAD

**Issue by fjouault** [Aymkdn/assistant-freebox#22]
Bonjour,

Le code de récupération des chaînes utilise l'URL suivante :
https://www.free.fr/freebox/js/datas/tv/jsontv.js
qui ne liste pas les chaînes optionnelles, quant à elles accessibles, dans le même format, à l'URL suivante :
https://www.free.fr/freebox/js/datas/tv/jsontvo.js

Idéalement, la liste des chaînes (le fichier chaines_free.json) pourrait être construite à partir des deux listes ci-dessus et pas uniquement de la première. Canal+ n'aurait plus besoin d'être ajoutée "à la main" dans le code et toutes les autres chaînes optionnelles seraient aussi disponibles.

Cordialement,

Frédéric

**Comment by Aymkdn** [comment]
Si j'ai pas trop merdé, ça devrait maintenant prendre en compte ce second fichier (v2.0.13 juste publiée).

**Comment by fjouault** [comment]
Ça a l'air de bien fonctionner. Merci.
