### ISSUE TITLE
Contrôle Freebox

### ISSUE THREAD

**Issue by rick443** [Aymkdn/assistant-freebox#24]
Bonjour,
Encore un sujet : 
j'essai de piloter la freebox via un script power shell

J'arrive dans un premier temps à authentifier "Mon PC" sur la free.
J'obtiens le Token.
J'arrive à ouvrir une session (token session)

Mais je n'arrive pas à lancer une commande pour allumer la free, choisir le mode TV en bien encore choisir une chaine.

pourriez-vous me donner un exemple d'URL (sans aucune variable svp !) pour allumer la free...
peut on  tout mettre dans l'URL ?
ex: http://mafreebox.freebox.fr/...........

j'ai essayé de décortiquer le plugin assistant-freebox, mais les appels de procèdures me perdent.

Merci pour votre réponse

**Comment by Aymkdn** [comment]
Avec [l'API du Player](https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Player-API) tu n'auras qu'un nombre limité d'opérations, et c'est un peu fastidieux.

Si tu veux imiter le plugin Freebox, alors tu peux simplement utiliser l'API HTTP qui est basé sur le code télécommande. Il y a un tas de sites qui expliquent comment faire, comme http://tutoriels.domotique-store.fr/content/51/90/fr/api-de-la-freebox-tv-_-player-v5-_-v6-via-requ%C3%AAtes-http.html

**Comment by rick443** [comment]
Super ! Merci, c'est exactement ce que je cherchais !   en plus simple !

**Comment by Aymkdn** [comment]
Je ferme l'issue. Si tu as d'autres questions tu peux les poser ici
