### ISSUE TITLE
NAS LinkStation 

### ISSUE THREAD

**Issue by MelvinNau** [Aymkdn/assistant-freebox#3]
Salut, merci pour le travail effectué et bonne année ! =)

Je me permet de te demander quelques pistes concernant ton [assistant-freebox](https://github.com/Aymkdn/assistant-freebox).

On peut donc gerer le dossier `search_path`, avec par defaut le "Disque Dur", j'aimerais donc maintenant mettre mon NAS qui est bien visible depuis Disques->Mes Disques, dans les Serveurs UPnP.

J'ai fais plusieurs test mais qui aboutissent toujours à une réponse négative du Google Home.
(En restant sur "Disque Dur/Vidéos/, tout est bon et c'est déjà génial ! )
Tu penses que cela est possible ? Merci

**Comment by Aymkdn** [comment]
Salut,

Voir ma réponse ici : https://github.com/Aymkdn/assistant-plugins/issues/66

**Comment by MelvinNau** [comment]
Je suis passé à coté de celle là ! 
Merci bien

**Comment by Aymkdn** [comment]
Cela dit, ta question est de savoir comment on peut s'y rendre, ou alors de pouvoir utiliser une commande comme `OK Google, va dans le dossier Machin`, avec `Machin` qui serait sur ton serveur UPnP ?

Car la Freebox Server nous donne accès à son propre disque dur, et c'est comme ça que je peux chercher un dossier. Je vais regarder si on peut accéder à d'autres entités, mais ça m'étonnerait...

**Comment by MelvinNau** [comment]
C'est bien ca "OK Google, va dans le dossier Machin, avec Machin qui serait
sur ton serveur UPnP ?" ! Ca serait génial, si tu tombe sur une piste ou
une amorce de réflexion je me ferais un plaisir de continuer et de partager
mon expérience si besoin =)

**Comment by Aymkdn** [comment]
J'ai regardé, et je ne vois pas de solution pour ça...

**Comment by Aymkdn** [comment]
Je ferme cet issue puisque pas de solution à proposer. Si j'ai une idée de génie je te le ferai savoir :-)

**Comment by MelvinNau** [comment]
Super !

A la prochaine =)
