### ISSUE TITLE
Pré-requis pour raspberry pi 3

### ISSUE THREAD

**Issue by jppmedia** [Aymkdn/assistant-freebox#4]
Bonjour,
Quels sont les pré-requis pour une installation sur un raspberry pi 3 ?
Merci :)
jp

**Comment by Aymkdn** [comment]
Il n'y a pas de pré requis.... Je ne comprends pas ta question...

**Comment by jppmedia** [comment]
j'ai un raspberry pi 3 et une carte sd avec raspian strech installé dessus, que me faut il de plus pour faire fonctionner ton plugin ?

**Comment by Aymkdn** [comment]
Bhein rien. Il faut suivre le guide d'installation c'est tout.

**Comment by Aymkdn** [comment]
Évidemment ton Raspberry doit être connecté à Internet/ton réseau local...

**Comment by jppmedia** [comment]
ok, donc j'ai un raspberry pi 3, un micro, des haut-parleurs, raspian d'installer, une freebox(évidemment !) plus ton plugins, et ça fonctionne ?

**Comment by Aymkdn** [comment]
Normalement oui.

**Comment by jppmedia** [comment]
Pas besoin d'installer le Google Assistant SDK ?

**Comment by Aymkdn** [comment]
Non.... tout est expliqué là : https://github.com/Aymkdn/assistant-plugins/wiki/Installation-de-assistant-plugins-sur-RaspberryPi

**Comment by jppmedia** [comment]
Ok merci de ta patience ! j'ai un peu de mal des fois a comprendre ce qui parait simple, désolé ! je vais essayer ton plugin.

**Comment by Aymkdn** [comment]
Si tu as des soucis dans l'installation, tu peux poster là : https://github.com/Aymkdn/assistant-plugins/issues

En attendant, je ferme cet issue là ;-)
