### ISSUE TITLE
Erreur: le code télécommande

### ISSUE THREAD

**Issue by jboss38** [Aymkdn/assistant-freebox#5]
`[assistant-freebox] Erreur: le code télécommande n'a pas été fourni dans le fichier configuration.json
`

J'ai suivi ces instructions : 

> Paramètre code_telecommande
> Allumer la Freebox, aller complètement à gauche dans la section Réglages, puis descendre jusqu'à Système, puis dans Informations Freebox Player et Server.
> 
> Dans le premier onglet vous trouverez le code télécommande réseau. Inscrire ce nombre dans le fichier de configuration.

Cependant je ne retombe pas sur les mêmes choses.

Je possède une Freebox Player mini avec la dernière version, impossible de trouver "code télécommande"

**Comment by Aymkdn** [comment]
Ce n'est que pour la Freebox Révolution...

**Comment by jboss38** [comment]
Arf :'(

Serait-il possible avec la Freebox crystal (mini) un jour ?

**Comment by Aymkdn** [comment]
Si Free ne propose pas les mêmes possibilités que sur la Révolution, alors non.

**Comment by jboss38** [comment]
Okey, avec l'application Android TV il est possible de contrôler la télé via son téléphone, il utilise une fonctionnalité de parrainage que je ne connais pas mais très efficace, est-ce que il serai possible d'utiliser cette même méthode ?

**Comment by Aymkdn** [comment]
N'ayant pas qu'une Freebox Révolution il m'est impossible de pouvoir tester d'autres box de Free et donc de les piloter (si cela est possible).

**Comment by Aymkdn** [comment]
Donc je ne dis pas que c'est totalement impossible, mais que ce n'est pas moi qui pourrai développer un tel plugin puisque je ne possède pas ce matériel. Il faut donc qu'il y ait d'autres développeurs qui se penchent dessus !

**Comment by jboss38** [comment]
Okey, si cela t'intéresse je peu peut-être te mettre à disposition le matériel :)

**Comment by Aymkdn** [comment]
Euh non... ce n'est pas le genre de matériel qu'on peut prêter !

J'ai des amis qui ont la Freebox Crystal, et d'autres la Freebox Mini 4k. Mais bon, faudrait que je passe (au moins) une journée chez eux à ne faire que bidouiller avec mon PC. Bof quoi :-)

**Comment by jboss38** [comment]
Petite info : 
![image](https://user-images.githubusercontent.com/6693379/34784337-43489cce-f62e-11e7-8972-715200af66cf.png)

Source : https://support.google.com/googlehome/answer/7214982?hl=fr

La Freebox crystal (mini 4K) est en réalité une Android TV.

A voir donc, lorsque celle ci sera compatible.

**Comment by Aymkdn** [comment]
OK.

Je ferme l'issue donc :-)
