### ISSUE TITLE
allumage freebox player

### ISSUE THREAD

**Issue by cg62200** [Aymkdn/assistant-freebox#6]
Bonjour, j'ai suivi les instructions sans difficultés et la c'est le bug comme dirait google home.
Tout fonctionne correctement sauf l'allumage. J'ai tout redémarrer et J'ai essayé de refaire l'applets IFTTT.
Rien y fait. 
Message : "erreur : le freebox player ne repond pas! essayez de changer le parametre hd1 en hd2 etc....
L'installation est faite sur un pc en ethernet avec seven.
En tout cas un grand bravo!! pour votre travail et un grand merci!!

**Comment by Aymkdn** [comment]
Est-ce que les autres commandes fonctionnent ? (comme changement de chaine, aller dans Mes Vidéos, éteindre, etc)

**Comment by cg62200** [comment]
Oui tout est fonctionnel même éteindre.

**Comment by Aymkdn** [comment]
Quand tu éteins la Freebox, elle se met en veille ou s'arrête complètement ? Car elle doit rester en mode veille pour que ça fonctionne (dans les menus de la Freebox Player : **Réglages** > **Système** > **Gestion de l'Énergie** > **Action par défaut de la touche d'extinction** > **Mettre en veille**)

**Comment by cg62200** [comment]
ah ok c'est donc ça je vais essayer.
Impec c'était bien ça. merci
