### ISSUE TITLE
Monte le son de X

### ISSUE THREAD

**Issue by cg62200** [Aymkdn/assistant-freebox#7]
Bonjour, Quand je veux monter ou descendre le son de x barres ça ne fonctionne pas. ça descend ou monte d'une barre.
J'ai activé le hdmi cec pour allumer et gérer le son de mon ampli et ma tv quand la freebox s'allume. 
Cela peut provenir de ça?
C'est quoi le maximum de barre que l'on peut annoncer?

**Comment by Aymkdn** [comment]
Quand tu augmentes le son avec la télécommande de la Freebox, est-ce que ça l'augmente sur ton ampli ?

Je me rappelle quelqu'un avait le même soucis... mais je n'arrive pas à le retrouver...

**Comment by cg62200** [comment]
Oui, ça me met la barre bleu de la freebox sur la droite de l'ecran et juste en dessous hdmi cec et le chiffre du niveau sonore de l'ampli. Pourtant la commande et bien lancer depuis pushbullet car je vois plusieurs fois "http://hd1............&key=vol_inc".dans fenetre dos.

**Comment by Aymkdn** [comment]
Ce que tu peux tenter, est de changer [la configuration](https://aymkdn.github.io/assistant-plugins/?plugin=freebox#configuration) en ajoutant le paramètre `delay_volume` dans ton fichier `configuration.json` et en mettant genre `"delay_volume":500` (donc 500ms entre l'envoi de chaque changement de volume).

**Comment by cg62200** [comment]
Encore bravo. cela fonctionne mais le nombre de barre n'est pas proportionnel . pour 10 cela fait 5 barres réel. J'ai essayé en augmentant les ms mais rien y fait.
Cela n’empêche pas sont utilisation vraiment super.

**Comment by Aymkdn** [comment]
Cool 😊
