### ISSUE TITLE
assistant-freebox ko suite maj freebox 3.5

### ISSUE THREAD

**Issue by iceempror** [Aymkdn/assistant-freebox#8]
Bonsoir,
Suite à la maj de la freebox ce jour en 3.5.0, l'assistant ne peut plus recuperer les chaines tv 

[assistant] Assistant v2.0.2 : Chargement en cours...
[assistant] 6 plugins trouvés.
[assistant] Chargement du plugin 'freebox' (v2.0.7)
[assistant-freebox] Récupération des chaines télé...
{ Error: EACCES: permission denied, open '/opt/assistant-plugins/node_modules/assistant-freebox/chaines_free.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1291:33)
    at /opt/assistant-plugins/node_modules/assistant-freebox/freebox.js:98:10
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/opt/assistant-plugins/node_modules/assistant-freebox/chaines_free.json' }
bash-4.3$

**Comment by Aymkdn** [comment]
Ouais car l'utilisateur avec lequel tu lances le programme n'a pas le droit d'écriture sur `/opt/assistant-plugins/node_modules/assistant-freebox/`

Tu peux essayer de faire : 
```bash
chmod 777 /opt/assistant-plugins/node_modules/assistant-freebox/

**Comment by iceempror** [comment]
Oups, désolé, je n'ai meme pas vérifié ca en premier.
Peux tu m'indiquer la version de node js minimale requise pour que le code fonctionne ?

**Comment by Aymkdn** [comment]
Je crois que ça fonctionne dès la v8 de Node (peut-être des versions antérieures aussi)... Mais je recommande d'utiliser la dernière disponible quand même !

**Comment by iceempror** [comment]
Ok parfait, je tourne avec la 8.9.4.
Merci pour ton aide.
