### ISSUE TITLE
Se deplacer de X

### ISSUE THREAD

**Issue by NiamorLyon** [Aymkdn/assistant-freebox#9]
Salut et merci pour ce plugin top 👍

Moi je l'utilise avec Cortana ;-) et ca fonctionne du tonnerre

Tu as deja bien mache le travail avec la recherche de dossier (freebox_folder XXX) ...
mais j'aurai un souhait a formuler ...
... dans le cas d'une serie ... on a plein d'episode ... (tu sens ou je veux en venir ;-) ...
... est ce que ca serait possible de pouvoir descendre de N fois quand on est dans un dossier
et par reciproque de monter N fois
voir d'aller a droit et a gauche de N
... que l'on lancerait avec une commande du genre :
"lance l'episode N" (freebox_down N,ok)
... puisque avec IFTTT "Say a phrase with number" on peut recuperer un chiffre pour le passer a pushbullet

Encore plus top .... ca serait que la fonctionnalite ... rechercher dans le nom du fichier au format SxxEnn (Saison xx Episode nn) l'episode en question (je crois pas qu'on puisse cumuler avec la saison .. dommage)
...mais la j'en demande trop ;-P

Voila ... si c'est dans le domaine du faisable.

Cdl
Romain

**Comment by NiamorLyon** [comment]
Hum ... je viens de m'apercevoir en regardant le code qu'il y a qq chose qui est decrit nul part ... c'est l'utilisation de "*" pour repeter une commande.
... du coup pour "lance l'épisode #" j'utilise `"freebox_left,down*#,up,ok"` et le tour est joue

**Comment by Aymkdn** [comment]
Oui voilà, tu peux en effet utiliser `*` :-)

Personnellement, après chaque visionnage d'un épisode, je l'efface. Du coup j'ai des répertoires au nom de mes séries et je dis simplement : "OK Google, lance la série The Walking Dead". Il cherche le répertoire avec ce nom, puis va me lancer le premier fichier listé (qui est donc l'épisode que je n'ai pas encore vu).

J'avais pensé à ce système de "Saison X épisode Y", mais j'y vois quelques problèmes : 
- si le système le plus courant est SxxEyy, ce n'est pas toujours le cas (on ne trouve pas ce format tout le temps, selon la source de téléchargement)
- j'ai du mal à croire que quelqu'un se souvienne du numéro du dernier épisode vu d'une série ^^
- selon le nombre d'épisodes conservés, et le classement de ceux-ci (en vrac dans un seul répertoire, ou dans des sous-répertoires classés par saison), la recherche peut s'avérer longue

Le truc qui aurait pu être pratique, c'est que Free fournisse dans [son API](https://dev.freebox.fr/sdk/os/fs/#) un moyen de voir les fichiers déjà lus (comme c'est le cas dans l'interface où on a une marque verte qui apparait), et du coup on pourrait dire : "OK Google, lance le dernier épisode de The Walking Dead" qui irait chercher le premier fichier non lu dans le répertoire de ce nom ; mais je ne crois pas avoir vu cette possibilité dans leur API...

**Comment by NiamorLyon** [comment]
Effectivement ... la coche verte "Video Lu" semble etre une fonctionnalite de l'application du player. (On ne peut d'ailleurs pas cocher ou decocher manuellement ...)

Donc dommage...
